version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build_and_test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m venv data4tweets-env
            . data4tweets-env/bin/activate
            export FLASK_APP=app
            export FLASK_ENV=development
            echo PYTHONPATH
            echo $PWD
          environment:
            PYTHONPATH: /home/circleci/project

      # Run tests
      - run:
          name: Run tests
          command: |
            . data4tweets-env/bin/activate
            pytest

workflows:
  build-and-test:
    jobs:
      - build_and_test
